apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cfdeployments.fissile.suse.com
spec:
  group: fissile.suse.com
  names:
    kind: CFDeployment
    listKind: CFDeploymentList
    plural: cfdeployments
    singular: cfdeployment
  scope: Namespaced
  version: v1alpha1
